default: &default
    adapter: postgresql
    pool: 5
    timeout: 5000

development:
    <<: *default
    encoding: unicode
    database: clarity_db
    host: localhost

production:
    <<: *default
    encoding: utf8
    database: <%= ENV['RDS_DB_NAME'] %>
    username: <%= ENV['RDS_USERNAME'] %>
    password: <%= ENV['RDS_PASSWORD'] %>
    host: <%= ENV['RDS_HOSTNAME'] %>
    port: <%= ENV['RDS_PORT'] %>
