default: &default
    adapter: postgresql
    pool: 5
    timeout: 5000

development:
    <<: *default
    encoding: unicode
    database: clarity_db
    host: localhost

production:
    <<: *default
    url: claritydev.cr0ishq3kdtu.us-west-2.rds.amazonaws.com
    encoding: unicode
    database: <%= ENV['RDS_DB_NAME'] %>
    username: <%= ENV['RDS_USERNAME'] %>
    password: <%= ENV['RDS_PASSWORD'] %>
    host: <%= ENV['RDS_HOSTNAME'] %>
    port: 5432
